#ifndef _STRING_TABLE_H
#define _STRING_TABLE_H


typedef enum {
    STRING_INDEX_INVALID = 0,
    STRING_INDEX_FIRST = 1,

    // 菜单
    MENU_FLOATING_WINDOW = 1,
    MENU_TRAY_ICON,
    MENU_START_WORK,
    MENU_SHORT_RELAX,
    MENU_LONG_RELAX,
    MENU_PAUSE,
    MENU_RESET,
    MENU_OPTION,
    MENU_ABOUT,
    MENU_EXIT,

    // 通知栏图标提示
    TRAY_ICON_TIPS_WORK,
    TRAY_ICON_TIPS_SHORT_RELAX,
    TRAY_ICON_TIPS_LONG_RELAX,
    TRAY_ICON_TIPS_PAUSE,

    // OPTION对话框
    OPTION_CAPTION,
    OPTION_BUTTON_RESET,
    OPTION_BUTTON_RESET_TIP,
    OPTION_BUTTON_APPLY,
    OPTION_BUTTON_APPLY_TIP,
    OPTION_BUTTON_SAVE,
    OPTION_BUTTON_SAVE_TIP,
    OPTION_CHECK_FAIL_CAPTION,

    OPTION_PAGE_TIME,
    OPTION_PAGE_NOTIFY,
    OPTION_PAGE_AUTO_AWAY,
    OPTION_PAGE_LANGUAGE,
    OPTION_PAGE_MISC,

    OPTION_TIME_SHORT_RELAX,
    OPTION_TIME_SHORT_RELAX_WD,
    OPTION_TIME_SHORT_RELAX_WD_UNIT,
    OPTION_TIME_SHORT_RELAX_SRD,
    OPTION_TIME_SHORT_RELAX_SRD_UNIT,
    OPTION_TIME_LONG_RELAX,
    OPTION_TIME_LONG_RELAX_LRF,
    OPTION_TIME_LONG_RELAX_LRF_UNIT,
    OPTION_TIME_LONG_RELAX_LRD,
    OPTION_TIME_LONG_RELAX_LRD_UNIT,
    OPTION_TIME_TIPS,
    OPTION_TIME_SETTING_REFERENCE,
    OPTION_TIME_CHECK_FAIL_WORK_DURATION,
    OPTION_TIME_CHECK_FAIL_SHORT_RELAX_DURATION,
    OPTION_TIME_CHECK_FAIL_LONG_RELAX_DURATION,

    OPTION_NOTIFY_PRENOTIFY,
    OPTION_NOTIFY_LOCK_INPUT,
    OPTION_NOTIFY_LOCK_INPUT_KEYBOARD,
    OPTION_NOTIFY_LOCK_INPUT_MOUSE,
    OPTION_NOTIFY_LOCK_INPUT_BOTH,
    OPTION_NOTIFY_SCREEN_MASK,
    OPTION_NOTIFY_SCREEN_MASK_TRANSPARENCY,
    OPTION_NOTIFY_SCREEN_MASK_TRANSPARENCY_TRANSPARENT,
    OPTION_NOTIFY_SCREEN_MASK_TRANSPARENCY_OPAQUE,
    OPTION_NOTIFY_SCREEN_MASK_COLOR,
    OPTION_NOTIFY_SCREEN_MASK_COLOR_BLACK,
    OPTION_NOTIFY_SCREEN_MASK_COLOR_CUSTOM,
    OPTION_NOTIFY_SCREEN_MASK_ANIMATION,
    OPTION_NOTIFY_SCREEN_MASK_ANIMATION_OFF,
    OPTION_NOTIFY_SCREEN_MASK_ANIMATION_FAST,
    OPTION_NOTIFY_SCREEN_MASK_ANIMATION_MEDIUM,
    OPTION_NOTIFY_SCREEN_MASK_ANIMATION_SLOW,
    OPTION_NOTIFY_MULTIMON,
    OPTION_NOTIFY_MULTIMON_DARKER_SCREEN,
    OPTION_NOTIFY_MULTIMON_DARKER_SCREEN_MASTER,
    OPTION_NOTIFY_MULTIMON_DARKER_SCREEN_CURSOR,
    OPTION_NOTIFY_MULTIMON_DARKER_SCREEN_ALL,
    OPTION_NOTIFY_MULTIMON_NOTIFY_WINDOW,
    OPTION_NOTIFY_MULTIMON_NOTIFY_WINDOW_MASTER,
    OPTION_NOTIFY_MULTIMON_NOTIFY_WINDOW_CURSOR,

    OPTION_AUTOAWAY_AUTO_PAUSE,
    OPTION_AUTOAWAY_AUTO_PAUSE_AFTER,
    OPTION_AUTOAWAY_AUTO_PAUSE_IDLE,
    OPTION_AUTOAWAY_AUTO_PAUSE_FULLSCREEN,
    OPTION_AUTOAWAY_AUTO_RESET,
    OPTION_AUTOAWAY_AUTO_RESET_AFTER,
    OPTION_AUTOAWAY_AUTO_RESET_IDLE,
    OPTION_AUTOAWAY_CHECK_FAIL_AUTO_RESET_INTERVAL,

    OPTION_LANGUAGE_SELECT,
    OPTION_LANGUAGE_CHECK_FAIL_UNAVAILABLE,
    OPTION_LANGUAGE_TIPS,

    OPTION_MISC_LOCK_COMPUTER,
    OPTION_MISC_CLOSE_MONITOR,
    OPTION_MISC_SHOW_FLOATING_WINDOW,
    OPTION_MISC_SHOW_TRAY_ICON,
    OPTION_MISC_LOG,
    OPTION_MISC_LOG_LEVEL,
    OPTION_MISC_LOG_FILE_SIZE,
    OPTION_MISC_STARTUP_WITH_WINDOWS,
    OPTION_MISC_CHECK_FAIL_STARTUP_WITH_WINDOWS,

    // ABOUT对话框
    ABOUT_CAPTION,
    ABOUT_PAGE_ABOUT,
    ABOUT_PAGE_THANKS,
    ABOUT_PAGE_CHANGELOG,
    ABOUT_PAGE_STATISTICS,
    ABOUT_PAGE_DONATE,

    ABOUT_ABOUT_DEDICATE,
    ABOUT_ABOUT_APPINFO,
    ABOUT_ABOUT_APPINFO_APPNAME,
    ABOUT_ABOUT_APPINFO_VERSION,

    ABOUT_THANKS_CONTRIBUTERS,
    ABOUT_THANKS_EXTERNALS,

    ABOUT_CHANGELOG_HISTORY,

    ABOUT_STATISTICS_ITEM,
    ABOUT_STATISTICS_COUNTER,
    ABOUT_STATISTICS_RATIO,
    ABOUT_STATISTICS_TIME_HEADLINE,
    ABOUT_STATISTICS_TIME_TOTAL,
    ABOUT_STATISTICS_TIME_WORK,
    ABOUT_STATISTICS_TIME_SRELAX,
    ABOUT_STATISTICS_TIME_LRELAX,
    ABOUT_STATISTICS_TIME_PAUSE,
    ABOUT_STATISTICS_TIME_RESET,
    ABOUT_STATISTICS_RELAX_HEADLINE,
    ABOUT_STATISTICS_RELAX_SRELAX,
    ABOUT_STATISTICS_RELAX_LRELAX,
    ABOUT_STATISTICS_RELAX_DELAYED,
    ABOUT_STATISTICS_RELAX_SKIPPED,

    ABOUT_DONATE_DONATION_APPEAL,
    ABOUT_DONATE_DONATION_LIST_HEADER,
    ABOUT_DONATE_DONATION_TIPS,

    // TrayWindow
    TRAY_WINDOW_CAPTION_NEXT_RELAX,
    TRAY_WINDOW_CAPTION_SHORT_RELAX,
    TRAY_WINDOW_CAPTION_LONG_RELAX,
    TRAY_WINDOW_DELAY,
    TRAY_WINDOW_DELAY_TIPS,
    TRAY_WINDOW_SKIP,
    TRAY_WINDOW_SKIP_TIPS,
    TRAY_WINDOW_HIDE,
    TRAY_WINDOW_HIDE_TIPS,

    STRING_INDEX_LAST = TRAY_WINDOW_HIDE_TIPS,
    STRING_INDEX_NUM = STRING_INDEX_LAST
} StrIdx;

#define STRING_LENGTH               (1023)


class CStringTable
{
public:
    BOOL    LoadStringTable(const char *pchLangFile, const char *pchLanguage);
    void    LoadDefaultString();
    void    StringTableReformat();
    char*   GetStr(StrIdx eIndex);
private:
    char    aachStringTable[STRING_INDEX_NUM + 1][STRING_LENGTH + 1];
};


#endif