//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by RelaxReminder.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_RELAXREMINDER_DIALOG        102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_OPTION               129
#define IDD_DIALOG_OPTION_TIME          130
#define IDD_DIALOG_OPTION_NOTIFY        131
#define IDR_MENU_TRAYMENU               133
#define IDI_ICON1                       137
#define IDI_ICON2                       138
#define IDI_ICON3                       139
#define IDI_ICON4                       140
#define IDI_ICON5                       141
#define IDI_ICON6                       142
#define IDI_ICON7                       143
#define IDI_ICON8                       144
#define IDI_ICON9                       145
#define IDI_ICON10                      146
#define IDI_ICON11                      147
#define IDI_ICON12                      148
#define IDI_ICON13                      149
#define IDI_ICON14                      150
#define IDI_ICON15                      151
#define IDI_ICON16                      152
#define IDI_ICON17                      153
#define IDI_ICON18                      154
#define IDI_ICON19                      155
#define IDI_ICON20                      156
#define IDI_ICON21                      157
#define IDI_ICON22                      158
#define IDI_ICON23                      159
#define IDI_ICON24                      160
#define IDI_ICON25                      161
#define IDI_ICON26                      162
#define IDI_ICON27                      163
#define IDI_ICON28                      164
#define IDI_ICON29                      165
#define IDI_ICON30                      166
#define IDI_ICON31                      167
#define IDI_ICON32                      168
#define IDI_ICON33                      169
#define IDI_ICON34                      170
#define IDI_ICON35                      171
#define IDI_ICON36                      172
#define IDI_ICON37                      173
#define IDI_ICON38                      174
#define IDI_ICON39                      175
#define IDI_ICON40                      176
#define IDI_ICON41                      177
#define IDI_ICON42                      178
#define IDI_ICON43                      179
#define IDI_ICON44                      180
#define IDI_ICON45                      181
#define IDD_DIALOG_OPTION_AUTO_AWAY     182
#define IDI_ICON_RESET_01               184
#define IDI_ICON_RESET_02               185
#define IDD_DIALOG_TRAY_WINDOW          186
#define IDD_DIALOG_OPTION_ABOUT         187
#define IDD_DIALOG_OPTION_STATISTIC     188
#define IDD_DIALOG_ABOUT                189
#define IDD_DIALOG_STATISTIC            190
#define IDD_DIALOG_REGISTER             192
#define IDD_DIALOG_ABOUT_ABOUT          194
#define IDD_DIALOG_ABOUT_THANKS         196
#define IDD_DIALOG_ABOUT_STATISTICS     197
#define IDD_DIALOG_ABOUT_REGISTRATION   198
#define IDD_DIALOG_PLUGINS_MANAGER      199
#define IDD_DIALOG_DARKER_SCREEN        200
#define IDD_DIALOG_OPTION_MISC          203
#define IDD_DIALOG_ABOUT_DEBUG          204
#define IDB_BITMAP_WIZARD_LOGO_IN       207
#define IDD_DIALOG_ABOUT_CHANGELOG      208
#define IDD_DIALOG_OPTION_LANGUAGE      209
#define IDD_DIALOG_ABOUT_DONATE         211
#define IDD_DIALOG_ABOUT_DONATE_DONATE_LIST 212
#define IDD_DIALOG_ABOUT_DONATE_FREE_LICENSE 213
#define IDD_DIALOG_ABOUT_DONATE_DONATED_LICENSE 214
#define IDB_BITMAP_PAYPAL_LOGO          215
#define IDB_BITMAP_ALIPAY_LOGO          216
#define IDD_DIALOG_SETUP_WIZARD         217
#define IDD_DIALOG_SETUP_WIZARD_WELCOME 218
#define IDD_DIALOG_OPTION_MULTI_MON     219
#define IDB_BITMAP_WIZARD_LOGO_OUT      221
#define IDB_BITMAP_LOGOa                222
#define IDB_BITMAP_LOGO                 222
#define IDC_STATIC_TIMETIPS             1001
#define IDC_BUTTON_PAUSE                1002
#define IDC_BUTTON_START_WORK           1003
#define IDC_BUTTON_RESET                1004
#define IDC_TAB_OPTION                  1005
#define IDC_STATIC_WORK_DURATION        1007
#define IDC_COMBO_WORK_DURATION         1008
#define IDC_STATIC_WORK_DURATION2       1009
#define IDC_COMBO_WORK_DURATION2        1010
#define IDC_COMBO_SHORT_RELAX_DURATION  1010
#define IDC_STATIC_WORK_DURATION3       1018
#define IDC_COMBO_WORK_DURATION3        1019
#define IDC_COMBO_LONG_RELAX_FREQUENCY  1019
#define IDC_BUTTON1                     1020
#define IDC_STATIC_WORK_DURATION4       1020
#define IDC_BUTTON_DELAY                1020
#define IDC_BUTTON_REGISTER             1020
#define IDC_BUTTON_ORDER                1020
#define IDC_BUTTON_ALL_TO_RIGHT         1020
#define IDC_BUTTON_CHECK_PASSWORD       1020
#define IDC_BUTTON_SELECT_ALL           1020
#define IDC_BUTTON_GET_FREE_LICENSE     1020
#define IDC_BUTTON_WIZARD_PREVIOUS      1020
#define IDC_BUTTON_NEXT                 1020
#define IDC_BUTTON2                     1021
#define IDC_COMBO_WORK_DURATION4        1021
#define IDC_BUTTON_APPLY                1021
#define IDC_COMBO_LONG_RELAX_DURATION   1021
#define IDC_BUTTON_ENTER_LICENSE        1021
#define IDC_BUTTON_SELECT_TO_RIGHT      1021
#define IDC_BUTTON_SKIP                 1021
#define IDC_BUTTON_SELECT_NONE          1021
#define IDC_BUTTON_GET_DONATE_LICENSE   1021
#define IDC_BUTTON_WIZARD_NEXT          1021
#define IDC_BUTTON3                     1022
#define IDC_BUTTON_SAVE                 1022
#define IDC_COMBO_AUTO_RESET_THRESHOLD  1022
#define IDC_BUTTON_SELECT_TO_LEFT       1022
#define IDC_BUTTON_HIDE                 1022
#define IDC_BUTTON_ACTIVATE_LICENSE     1022
#define IDC_BUTTON_ACTIVATE_FREE_LICENSE 1022
#define IDC_BUTTON_WIZARD_SKIP          1022
#define IDC_CHECK1                      1023
#define IDC_CHECK_PRENOTIFY             1023
#define IDC_BUTTON_ALL_TO_LEFT          1023
#define IDC_CHECK_FULLSCREEN_PAUSE      1023
#define IDC_CHECK2                      1024
#define IDC_CHECK_LOCK_INPUT            1024
#define IDC_CHECK3                      1025
#define IDC_CHECK_CLOSE_MONITOR         1025
#define IDC_CHECK_DARKER_SCREEN         1025
#define IDC_CHECK_ENABLE_LONG_RELAX     1026
#define IDC_CHECK_LOCK_COMPTER          1026
#define IDC_CHECK_ENABLE_AUTO_RESET     1027
#define IDC_CHECK_ENABLE_LOG            1027
#define IDC_CHECK_ENABLE_AUTO_PAUSE     1028
#define IDC_CHECK_AUTO_START            1028
#define IDC_COMBO_AUTO_PAUSE_THRESHOLD  1029
#define IDC_CHECK_SHOW_FLOATING_WINDOW  1029
#define IDC_STATIC_CAPTION              1030
#define IDC_CHECK_SHOW_TRAY_ICON        1030
#define IDC_STATIC_MSG                  1031
#define IDC_STATIC_SINGLE_MONITOR       1031
#define IDC_EDIT_HTTP_LINK              1032
#define IDC_STATIC_SINGLE_MONITOR2      1032
#define IDC_STATIC_DARKER_SCREEN_DISABLED 1032
#define IDC_EDIT_CONTRIBUTERS           1034
#define IDC_LIST_STATISTIC              1037
#define IDC_STATIC_REG_NAME             1040
#define IDC_STATIC_REG_LEVEL            1041
#define IDC_EDIT_REG_NAME               1042
#define IDC_STATIC_IDLE_SECONDS         1042
#define IDC_EDIT_REG_LEVEL              1043
#define IDC_STATIC_DEDICATED            1043
#define IDC_EDIT_REG_CODE               1044
#define IDC_EDIT_IDLE_SECONDS           1044
#define IDC_EDIT_REG_PRICE              1045
#define IDC_COMBO_REG_LEVEL             1046
#define IDC_TAB_ABOUT                   1047
#define IDC_STATIC_AUTHOR_HOMEPAGE      1048
#define IDC_STATIC_AUTHOR_EMAIL         1049
#define IDC_LIST_ACTIVE                 1052
#define IDC_LIST_INACTIVE               1053
#define IDC_EDIT_IMAGE_PATH             1054
#define IDC_RADIO_LOCK_KEYBOARD         1055
#define IDC_RADIO_LOCK_MOUSE            1056
#define IDC_RADIO_LOCK_BOTH             1057
#define IDC_STATIC_MASK                 1058
#define IDC_SLIDER_ALPHA                1059
#define IDC_STATIC_DARK_SCREEN_EXAMPLE_TEXT 1060
#define IDC_STATIC_DARKER_SCREEN_EXAMPLE_TEXT 1060
#define IDC_STATIC_DARKER_SCREEN_EXAMPLE_MASK 1061
#define IDC_STATIC_VERSION              1062
#define IDC_EDIT_TIMER_STATUS           1063
#define IDC_EDIT_LAPSED_SECONDS         1064
#define IDC_EDIT_SHORT_RELAXED          1065
#define IDC_EDIT_PASSWORD               1066
#define IDC_STATIC_PASSWORD             1067
#define IDC_STATIC_TIMER_STATUS         1068
#define IDC_STATIC_LAPSED_SECONDS       1069
#define IDC_STATIC_SHORT_RELAXED        1070
#define IDC_COMBO_LOG_LEVEL             1071
#define IDC_COMBO_LOG_FILE_SIZE         1072
#define IDC_STATIC_COPYRIGHT            1076
#define IDC_RADIO_ANIMATION_OFF         1077
#define IDC_RADIO_ANIMATION_FAST        1078
#define IDC_RADIO_ANIMATION_MEDIUM      1079
#define IDC_RADIO_ANIMATION_SLOW        1080
#define IDC_RADIO_COLOR_BLACK           1081
#define IDC_RADIO_COLOR_CUSTOM          1082
#define IDC_STATIC_CONTRIBUTERS         1086
#define IDC_STATIC_EXTERNAL_CONTRIBUTERS 1087
#define IDC_STATIC_TIPS                 1087
#define IDC_STATIC_COLOR                1088
#define IDC_STATIC_CHANGELOG            1092
#define IDC_STATIC_SHORT_RELAX          1093
#define IDC_STATIC_SHORT_RELAX_WD       1094
#define IDC_STATIC_SHORT_RELAX_WD_UNIT  1095
#define IDC_STATIC_SHORT_RELAX_SRD      1096
#define IDC_STATIC_SHORT_RELAX_SRD_UNIT 1097
#define IDC_STATIC_LONG_RELAX_LRF       1098
#define IDC_STATIC_LONG_RELAX_LRF_UNIT  1099
#define IDC_STATIC_LONG_RELAX_LRD       1100
#define IDC_STATIC_LONG_RELAX_LRD_UNIT  1101
#define IDC_STATIC_SETTING_REFERENCE    1102
#define IDC_STATIC_SCREEN_MASK_TRANSPARENCY 1103
#define IDC_STATIC_SCREEN_MASK_TRANSPARENCY_TRANSPARENT 1104
#define IDC_STATIC_SCREEN_MASK_TRANSPARENCY_OPAQUE 1105
#define IDC_STATIC_SCREEN_MASK_COLOR    1106
#define IDC_STATIC_SCREEN_MASK_ANIMATION 1107
#define IDC_STATIC_AUTO_PAUSE           1108
#define IDC_STATIC_AUTO_PAUSE_IDLE      1109
#define IDC_STATIC_AUTO_RESET           1110
#define IDC_STATIC_AUTO_RESET_IDLE      1111
#define IDC_STATIC_LOG_LEVEL            1112
#define IDC_STATIC_LOG_FILE_SIZE        1113
#define IDC_STATIC_DEDICATE             1114
#define IDC_STATIC_APPINFO              1115
#define IDC_STATIC_APPINFO_APPNAME      1116
#define IDC_STATIC_CONTAINER_CONTRIBUTERS 1117
#define IDC_STATIC_CONTAINER_EXTERNALS  1118
#define IDC_STATIC_HISTORY              1119
#define IDC_LIST_LANGUAGES              1120
#define IDC_STATIC_LANGUAGE_SELECT      1121
#define IDC_STATIC_NO_LANGUAGE_FILE     1122
#define IDC_LIST_PLUGINS                1123
#define IDC_RADIO_OPTION_TIME           1124
#define IDC_RADIO_OPTION_NOTIFY         1125
#define IDC_RADIO_OPTION_AUTO_AWAY      1126
#define IDC_RADIO_OPTION_LANGUAGE       1127
#define IDC_RADIO_OPTION_MISC           1128
#define IDC_STATIC_PLAT                 1129
#define IDC_RADIO_ABOUT_ABOUT           1130
#define IDC_RADIO_OPTION_MULTI_MON      1130
#define IDC_RADIO_ABOUT_THANKS          1131
#define IDC_STATIC_DONATE_CONTENT       1131
#define IDC_RADIO_ABOUT_CHANGELOG       1132
#define IDC_STATIC_DONATION_APPEAL      1132
#define IDC_RADIO_ABOUT_STATISTICS      1133
#define IDC_STATIC_DONATION_LIST_FRAME  1133
#define IDC_STATIC_DONATION_LIST        1134
#define IDC_RADIO_ABOUT_DONATE          1134
#define IDC_EDIT_LICENSE_INFO           1135
#define IDC_TAB_ABOUT_DONATE            1136
#define IDC_EDIT_FREE_LICENSE_CODE      1137
#define IDC_STATIC_FREE_LICENSE_CODE    1138
#define IDC_STATIC_FREE_LICENSE_HELP    1139
#define IDC_STATIC_DONATED_LICENSE_HELP 1140
#define IDC_STATIC_DONATED_LICENSE_CODE 1141
#define IDC_EDIT_DONATED_LICENSE_CODE   1142
#define IDC_BUTTON_ACTIVATE_DONATED_LICENSE 1143
#define IDC_STATIC_NOT_LICENSED_TIPS    1144
#define IDC_STATIC_UNLICENSED_TIPS      1144
#define IDC_STATIC_PAYPAL_LOGO          1145
#define IDC_STATIC_ALIPAY_LOGO          1146
#define IDC_STATIC_STEP_TIME            1147
#define IDC_STATIC_STEP_NOTIFY          1148
#define IDC_STATIC_STEP_AUTO_AWAY       1149
#define IDC_STATIC_STEP_LANGUAGE        1150
#define IDC_STATIC_WIZARD_PLAT          1151
#define IDC_STATIC_HLINE                1152
#define IDC_STATIC_NOTIFY_WINDOW        1153
#define IDC_STATIC_SCREEN_MASK          1154
#define IDC_RADIO_NOTIFY_MASTER         1155
#define IDC_RADIO_NOTIFY_CURSOR         1156
#define IDC_STATIC_MULTIMON             1156
#define IDC_RADIO_NOTIFY_ALL            1157
#define IDC_STATIC_MULTIMON_DARKER_SCREEN 1157
#define IDC_RADIO_MASK_MASTER           1158
#define IDC_STATIC_MULTIMON_NOTIFY_WINDOW 1158
#define IDC_RADIO_MASK_CURSOR           1159
#define IDC_RADIO_MULTIMON_DARKER_SCREEN_MASTER 1159
#define IDC_RADIO_MASK_ALL              1160
#define IDC_RADIO_NOTIFY_ALL2           1160
#define IDC_RADIO_MULTIMON_DARKER_SCREEN_CURSOR 1160
#define IDC_RADIO_MULTIMON_DARKER_SCREEN_ALL 1161
#define IDC_RADIO_MULTIMON_NOTIFY_WINDOW_MASTER 1162
#define IDC_RADIO_MULTIMON_NOTIFY_WINDOW_CURSOR 1163
#define IDC_STATIC_INTRO                1163
#define IDC_STATIC_START                1164
#define IDC_STATIC_DONATORS             1165
#define IDC_EDIT_DONATION_ACCOUNT       1167
#define ID_MENUITEM32771                32771
#define ID_MENUITEM32772                32772
#define ID_MENUITEM32773                32773
#define ID_MENU_START_WORK              32774
#define ID_MENU_SHORT_RELAX             32775
#define ID_MENU_LONG_RELAX              32776
#define ID_MENU_PAUSE                   32778
#define ID_MENU_RESET                   32779
#define ID_MENU_OPTION                  32780
#define ID_MENU_MAIN_WINDOW             32781
#define ID_MENU_ABOUT                   32782
#define ID_MENU_EXIT                    32783
#define ID_MENU_STATISTICS              32784
#define ID_MENUITEM32786                32786
#define ID_MENU_PLUGINS_MANAGER         32787
#define ID_MENU_TRAY_ICON               32789
#define ID_PLUGIN_BEGIN                 40000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        223
#define _APS_NEXT_COMMAND_VALUE         32790
#define _APS_NEXT_CONTROL_VALUE         1168
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
